<?php

namespace App\Models\Admin;

use App\Observers\Models\Admin\UsersObserver;
use Illuminate\Database\Eloquent\Model;

/**
* @property $id
* @property $name
* @property $email
* @property $email_verified_at
* @property $password
* @property $remember_token
* @property $created_at
* @property $updated_at
*/
class Users extends Model
{

    // if connection is empty ,use default connection
    protected $connection = '';

    protected $table = 'users';

    // default values
    protected $attributes = [
        
        'name' => '',
        'email' => '',
        'email_verified_at' => '',
        'password' => '',
        'remember_token' => '',
        'created_at' => '',
        'updated_at' => '',

    ];

    // converting attributes to common data types. like 'is_admin' => 'boolean',
    protected $casts = [

    ];

    public $rules = [
        
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::observe(UsersObserver::class);
    }
}
